/*
===========================================================
GENERATED FILE — DO NOT EDIT MANUALLY
Generated by:
scripts/generate-gallery.mjs

Source:
public/assets/gallery/

Run:
node scripts/generate-gallery.mjs
===========================================================
*/

export type GalleryCategory =
  | "Crowd"
  | "Dandiya"
  | "DJ / Music"
  | "Family"
  | "Garba"
  | "People"
  | "Stage"
  | "Team"
  | "Venue";

export interface GalleryItem {
  id: string;
  src: string;
  category: GalleryCategory;
  order: number;
}

export const gallery: GalleryItem[] = [
  {
    "id": "2025-crd-001",
    "src": "/assets/gallery/RR_2025_GAL_CRD_001.jpg",
    "category": "Crowd",
    "order": 1
  },
  {
    "id": "2025-crd-002",
    "src": "/assets/gallery/RR_2025_GAL_CRD_002.jpg",
    "category": "Crowd",
    "order": 2
  },
  {
    "id": "2025-crd-003",
    "src": "/assets/gallery/RR_2025_GAL_CRD_003.jpg",
    "category": "Crowd",
    "order": 3
  },
  {
    "id": "2025-crd-004",
    "src": "/assets/gallery/RR_2025_GAL_CRD_004.jpg",
    "category": "Crowd",
    "order": 4
  },
  {
    "id": "2025-crd-005",
    "src": "/assets/gallery/RR_2025_GAL_CRD_005.jpg",
    "category": "Crowd",
    "order": 5
  },
  {
    "id": "2025-crd-006",
    "src": "/assets/gallery/RR_2025_GAL_CRD_006.jpg",
    "category": "Crowd",
    "order": 6
  },
  {
    "id": "2025-crd-007",
    "src": "/assets/gallery/RR_2025_GAL_CRD_007.jpg",
    "category": "Crowd",
    "order": 7
  },
  {
    "id": "2025-dan-001",
    "src": "/assets/gallery/RR_2025_GAL_DAN_001.jpg",
    "category": "Dandiya",
    "order": 8
  },
  {
    "id": "2025-dan-002",
    "src": "/assets/gallery/RR_2025_GAL_DAN_002.jpg",
    "category": "Dandiya",
    "order": 9
  },
  {
    "id": "2025-dan-003",
    "src": "/assets/gallery/RR_2025_GAL_DAN_003.jpg",
    "category": "Dandiya",
    "order": 10
  },
  {
    "id": "2025-dan-004",
    "src": "/assets/gallery/RR_2025_GAL_DAN_004.jpg",
    "category": "Dandiya",
    "order": 11
  },
  {
    "id": "2025-dj-001",
    "src": "/assets/gallery/RR_2025_GAL_DJ_001.jpg",
    "category": "DJ / Music",
    "order": 12
  },
  {
    "id": "2025-dj-002",
    "src": "/assets/gallery/RR_2025_GAL_DJ_002.jpg",
    "category": "DJ / Music",
    "order": 13
  },
  {
    "id": "2025-fam-001",
    "src": "/assets/gallery/RR_2025_GAL_FAM_001.jpg",
    "category": "Family",
    "order": 14
  },
  {
    "id": "2025-fam-002",
    "src": "/assets/gallery/RR_2025_GAL_FAM_002.jpg",
    "category": "Family",
    "order": 15
  },
  {
    "id": "2025-fam-003",
    "src": "/assets/gallery/RR_2025_GAL_FAM_003.jpg",
    "category": "Family",
    "order": 16
  },
  {
    "id": "2025-fam-004",
    "src": "/assets/gallery/RR_2025_GAL_FAM_004.jpg",
    "category": "Family",
    "order": 17
  },
  {
    "id": "2025-fam-005",
    "src": "/assets/gallery/RR_2025_GAL_FAM_005.jpg",
    "category": "Family",
    "order": 18
  },
  {
    "id": "2025-fam-006",
    "src": "/assets/gallery/RR_2025_GAL_FAM_006.jpg",
    "category": "Family",
    "order": 19
  },
  {
    "id": "2025-fam-007",
    "src": "/assets/gallery/RR_2025_GAL_FAM_007.jpg",
    "category": "Family",
    "order": 20
  },
  {
    "id": "2025-fam-008",
    "src": "/assets/gallery/RR_2025_GAL_FAM_008.jpg",
    "category": "Family",
    "order": 21
  },
  {
    "id": "2025-fam-009",
    "src": "/assets/gallery/RR_2025_GAL_FAM_009.jpg",
    "category": "Family",
    "order": 22
  },
  {
    "id": "2025-fam-010",
    "src": "/assets/gallery/RR_2025_GAL_FAM_010.jpg",
    "category": "Family",
    "order": 23
  },
  {
    "id": "2025-fam-011",
    "src": "/assets/gallery/RR_2025_GAL_FAM_011.jpg",
    "category": "Family",
    "order": 24
  },
  {
    "id": "2025-gar-001",
    "src": "/assets/gallery/RR_2025_GAL_GAR_001.jpg",
    "category": "Garba",
    "order": 25
  },
  {
    "id": "2025-gar-002",
    "src": "/assets/gallery/RR_2025_GAL_GAR_002.jpg",
    "category": "Garba",
    "order": 26
  },
  {
    "id": "2025-ppl-001",
    "src": "/assets/gallery/RR_2025_GAL_PPL_001.jpg",
    "category": "People",
    "order": 27
  },
  {
    "id": "2025-ppl-002",
    "src": "/assets/gallery/RR_2025_GAL_PPL_002.jpg",
    "category": "People",
    "order": 28
  },
  {
    "id": "2025-ppl-003",
    "src": "/assets/gallery/RR_2025_GAL_PPL_003.jpg",
    "category": "People",
    "order": 29
  },
  {
    "id": "2025-ppl-004",
    "src": "/assets/gallery/RR_2025_GAL_PPL_004.jpg",
    "category": "People",
    "order": 30
  },
  {
    "id": "2025-ppl-005",
    "src": "/assets/gallery/RR_2025_GAL_PPL_005.jpg",
    "category": "People",
    "order": 31
  },
  {
    "id": "2025-ppl-006",
    "src": "/assets/gallery/RR_2025_GAL_PPL_006.jpg",
    "category": "People",
    "order": 32
  },
  {
    "id": "2025-ppl-007",
    "src": "/assets/gallery/RR_2025_GAL_PPL_007.jpg",
    "category": "People",
    "order": 33
  },
  {
    "id": "2025-ppl-008",
    "src": "/assets/gallery/RR_2025_GAL_PPL_008.jpg",
    "category": "People",
    "order": 34
  },
  {
    "id": "2025-ppl-009",
    "src": "/assets/gallery/RR_2025_GAL_PPL_009.jpg",
    "category": "People",
    "order": 35
  },
  {
    "id": "2025-ppl-010",
    "src": "/assets/gallery/RR_2025_GAL_PPL_010.jpg",
    "category": "People",
    "order": 36
  },
  {
    "id": "2025-ppl-011",
    "src": "/assets/gallery/RR_2025_GAL_PPL_011.jpg",
    "category": "People",
    "order": 37
  },
  {
    "id": "2025-ppl-012",
    "src": "/assets/gallery/RR_2025_GAL_PPL_012.jpg",
    "category": "People",
    "order": 38
  },
  {
    "id": "2025-ppl-013",
    "src": "/assets/gallery/RR_2025_GAL_PPL_013.jpg",
    "category": "People",
    "order": 39
  },
  {
    "id": "2025-ppl-014",
    "src": "/assets/gallery/RR_2025_GAL_PPL_014.jpg",
    "category": "People",
    "order": 40
  },
  {
    "id": "2025-ppl-015",
    "src": "/assets/gallery/RR_2025_GAL_PPL_015.jpg",
    "category": "People",
    "order": 41
  },
  {
    "id": "2025-stg-001",
    "src": "/assets/gallery/RR_2025_GAL_STG_001.jpg",
    "category": "Stage",
    "order": 42
  },
  {
    "id": "2025-stg-002",
    "src": "/assets/gallery/RR_2025_GAL_STG_002.jpg",
    "category": "Stage",
    "order": 43
  },
  {
    "id": "2025-team-001",
    "src": "/assets/gallery/RR_2025_GAL_TEAM_001.JPG",
    "category": "Team",
    "order": 44
  },
  {
    "id": "2025-team-002",
    "src": "/assets/gallery/RR_2025_GAL_TEAM_002.JPG",
    "category": "Team",
    "order": 45
  },
  {
    "id": "2025-team-003",
    "src": "/assets/gallery/RR_2025_GAL_TEAM_003.jpg",
    "category": "Team",
    "order": 46
  },
  {
    "id": "2025-ven-001",
    "src": "/assets/gallery/RR_2025_GAL_VEN_001.jpg",
    "category": "Venue",
    "order": 47
  }
];
