/*
===========================================================
RANGRATRI GALLERY GENERATOR
Phase A — Code Correctness
Iteration: A4

Purpose:
- Generate data/gallery.ts from the real gallery assets.
- Keep the generated data model synchronized with
  GalleryItem.
- Preserve exact asset filenames and extensions.
- Maintain stable category and ordering logic.
- Avoid generating fields that are no longer used.

Expected filename format:
RR_2025_GAL_<CATEGORY>_<NUMBER>.<extension>

Examples:
RR_2025_GAL_CRD_001.jpg
RR_2025_GAL_DAN_004.jpg
RR_2025_GAL_TEAM_001.JPG

Generated GalleryItem fields:
- id
- src
- category
- order

Removed:
- title
- featured

Those fields are intentionally not generated because they
are not required by the current gallery architecture.
===========================================================
*/

import fs from "fs";
import path from "path";

/*
-----------------------------------------------------------
DIRECTORIES
-----------------------------------------------------------
*/

const galleryDir = path.join(
  process.cwd(),
  "public",
  "assets",
  "gallery",
);

const outputFile = path.join(
  process.cwd(),
  "data",
  "gallery.ts",
);

/*
-----------------------------------------------------------
CATEGORY REGISTRY
-----------------------------------------------------------
The filename category code is converted into the public
GalleryCategory value used by the website.
-----------------------------------------------------------
*/

const categoryMap = {
  CRD: "Crowd",
  DAN: "Dandiya",
  DJ: "DJ / Music",
  FAM: "Family",
  GAR: "Garba",
  PPL: "People",
  STG: "Stage",
  TEAM: "Team",
  VEN: "Venue",
};

/*
-----------------------------------------------------------
ALLOWED IMAGE FORMATS
-----------------------------------------------------------
-----------------------------------------------------------
*/

const allowedExtensions = new Set([
  ".jpg",
  ".jpeg",
  ".png",
  ".webp",
]);

/*
-----------------------------------------------------------
VALIDATE SOURCE DIRECTORY
-----------------------------------------------------------
-----------------------------------------------------------
*/

if (!fs.existsSync(galleryDir)) {
  console.error(
    `Gallery directory not found: ${galleryDir}`,
  );

  process.exit(1);
}

/*
-----------------------------------------------------------
READ + SORT GALLERY FILES
-----------------------------------------------------------
Numeric sorting keeps:
001, 002, 003...
in the expected order instead of:
001, 010, 002...
-----------------------------------------------------------
*/

const files = fs
  .readdirSync(galleryDir)
  .filter((file) =>
    allowedExtensions.has(
      path.extname(file).toLowerCase(),
    ),
  )
  .sort((a, b) =>
    a.localeCompare(b, undefined, {
      numeric: true,
      sensitivity: "base",
    }),
  );

/*
-----------------------------------------------------------
GENERATE GALLERY ITEMS
-----------------------------------------------------------
*/

const items = [];

for (const file of files) {
  /*
  Expected:
  RR_2025_GAL_<CATEGORY>_<NUMBER>.<extension>
  */

  const match = file.match(
    /^RR_2025_GAL_([A-Z]+)_(\d+)\.[^.]+$/i,
  );

  if (!match) {
    console.warn(
      `Skipping unmatched file: ${file}`,
    );

    continue;
  }

  const code = match[1].toUpperCase();
  const number = Number(match[2]);

  /*
  ---------------------------------------------------------
  CATEGORY VALIDATION
  ---------------------------------------------------------
  */

  if (!Object.hasOwn(categoryMap, code)) {
    console.warn(
      `Unknown category "${code}" in ${file}`,
    );

    continue;
  }

  const category = categoryMap[code];

  /*
  ---------------------------------------------------------
  CREATE ITEM
  ---------------------------------------------------------
  */

  items.push({
    id: `2025-${code.toLowerCase()}-${String(
      number,
    ).padStart(3, "0")}`,

    /*
    Keep the actual filename exactly as it exists.
    This is important for case-sensitive production
    environments.
    */
    src: `/assets/gallery/${file}`,

    category,

    /*
    Stable generated order based on processed file order.
    */
    order: items.length + 1,
  });
}

/*
-----------------------------------------------------------
GENERATE TYPESCRIPT FILE
-----------------------------------------------------------
*/

const output = `/*
===========================================================
GENERATED FILE — DO NOT EDIT MANUALLY
Generated by:
scripts/generate-gallery.mjs

Source:
public/assets/gallery/

Run:
node scripts/generate-gallery.mjs
===========================================================
*/

export type GalleryCategory =
  | "Crowd"
  | "Dandiya"
  | "DJ / Music"
  | "Family"
  | "Garba"
  | "People"
  | "Stage"
  | "Team"
  | "Venue";

export interface GalleryItem {
  id: string;
  src: string;
  category: GalleryCategory;
  order: number;
}

export const gallery: GalleryItem[] = ${JSON.stringify(
  items,
  null,
  2,
)};
`;

/*
-----------------------------------------------------------
WRITE GENERATED FILE
-----------------------------------------------------------
*/

fs.writeFileSync(
  outputFile,
  output,
  "utf8",
);

/*
-----------------------------------------------------------
RESULT
-----------------------------------------------------------
*/

console.log(
  `Generated ${items.length} gallery items.`,
);

console.log(
  `Output: ${outputFile}`,
);